### ISSUE TITLE
Decoder modification for MS task type

### ISSUE THREAD

**Issue by UCT10** [Thinklab-SJTU/Crossformer#1]
Hi!
It's me again, thanks for the response on Openreview. Decided to check the Github for the source code, and here it is! Thanks for sharing!
I'm afraid I didn't understand which 2D vector do you mean. 

> As for your MS task, you need to modify the decoder, we can come up with two ways: 1) flatten the encoded 2D vector array into a 1D sequence to be used as keys and values of the multi-head self-attention; 2) use the same decoder as our original paper (i.e. each dimension will make a prediction of the target series), and sum over the predicted series of all dimensions to get the final result.

Output from encoder has shape of `b ts_d out_seg_num d_model`, i.e. [1024, 8, 8, 256], which modification to _DecoderLayer_ did you mean? Or is it in another layer?

I'm checking the second approach, which is pretty straightforward, seems that it works good too. 

P.S.
If you're interested, I've plugged Crossformer model into my exp class, and added [RevIN](https://openreview.net/pdf?id=cGDAkQo1C0p) layer ([this implementation](https://github.com/yuqinie98/PatchTST/blob/main/PatchTST_supervised/layers/RevIN.py)), it's been helpful to me with almost any model.

**Comment by YunhaoZhang-Mars** [comment]
For each instance, the output from the encoder has shape of `[ts_d, out_seg_num, d_model]`, where the `d_model` represents the number of hidden states. Therefore, the output is a 2D (`[ts_d, out_seg_num]`) vector array. The first approach is to reshape the `[b, ts_d, out_seg_num, d_model]` array into a `[b, ts_d * out_seg_num, d_model]` one, i.e. flatten the encoded 2D vector array into a 1D sequence. Then this reshaped array can be input to an original Transformer decoder.
P.S.
I think this flattening approach may perform worse than the second one as it does not distinguish the time and dimensions axes.
