### ISSUE TITLE
Can you help replacing naive attention with scaled_dot_product_attention()?

### ISSUE THREAD

**Issue by srogatch** [Thinklab-SJTU/Crossformer#13]
Hello,
Please, see https://github.com/Thinklab-SJTU/Crossformer/blob/fd0f601319e21d8ad6e058403927a11e75ed13ef/cross_models/attn.py#L23 :
```
def forward(self, queries, keys, values):
    B, L, H, E = queries.shape
    _, S, _, D = values.shape
    scale = self.scale or 1./sqrt(E)

    scores = torch.einsum("blhe,bshe->bhls", queries, keys)
    A = self.dropout(torch.softmax(scale * scores, dim=-1))
    V = torch.einsum("bhls,bshd->blhd", A, values)
    
    return V.contiguous()
```
I've tried to replace it with Flash Attention or similar in Pytorch:
```
def forward(self, queries, keys, values):
    # I'm not sure about the below - it's just a ChatGPT-assisted guess
    # B represents the batch size.
    # L is the sequence length for queries (or target sequence length).
    # H is the number of attention heads.
    # E is the depth (dimension) of each attention head for queries/keys.
    # S is the sequence length for keys/values (or source sequence length).
    # D is the depth (dimension) of each attention head for values.
    B, L, H, E = queries.shape
    _, S, _, D = values.shape

    y = torch.nn.functional.scaled_dot_product_attention(
        queries, keys, values, dropout_p=self.dropout_p if self.training else None)
    y = y.contiguous()
    return y
```
However, I'm getting `RuntimeError: The size of tensor a (10) must match the size of tensor b (4) at non-singleton dimension 1`.
Please, see the details here: https://stackoverflow.com/questions/76913572/how-to-replace-this-naive-code-with-scaled-dot-product-attention-in-pytorch

Can you please tell me what I'm missing or just go ahead and commit the proper change to your repository?

**Comment by YunhaoZhang-Mars** [comment]
I have checked pytorch document of scaled_dot_product_attention, and maybe you should permutate dimension 1 and 2 of queries, keys and values to make them [batch_size, head_num, seq_len, hidden_dim]. And remember to permutate back before the final returning.

**Comment by srogatch** [comment]
Thanks, it works! Though for me PyTorch says it can't use the Flash Attention kernel and it doesn't say the reason.
