### ISSUE TITLE
不同channel使用同一个linear层做projection的效果

### ISSUE THREAD

**Issue by ligrire** [Thinklab-SJTU/Crossformer#17]
您好，感谢您在github上公开分享研究成果。请问一下您在对patch做tokenize处理的时候，好像是不同channel的patch使用同一个linear层做projection的（其他channel independent的工作，如PatchTST似乎也是这样做的）。我想请问一下这样假设时间序列不同channel的意义相差很大的情况下，是否会对tokenization的输入效果产生影响？如果是每一个channel使用一个独立的linear层，您觉得会好一些吗

**Comment by YunhaoZhang-Mars** [comment]
您可以进行实验并以实验结果为准，我们使用shared layer是出于这样的考虑：现在用于时序预测的大多数neural model都存在overfitting的问题，如果对每一个channel使用一个linear layer会大幅增加参数量并加重overfitting，这一问题在高维数据集(ECL, Traffic)上可能会尤为明显。

**Comment by ligrire** [comment]
非常感谢您的回答！
