### ISSUE TITLE
过拟合严重

### ISSUE THREAD

**Issue by lilpeng-xxxl** [Thinklab-SJTU/Crossformer#18]
您好，感谢您在github上公开分享研究成果。当我将您的crossformer应用在我的任务上时出现较为严重的过拟合现象，请问改变代码中的哪个部分可以对我有帮助？

**Comment by YunhaoZhang-Mars** [comment]
可以尝试减小d_model, d_ff, n_heads, e_layers; 增大dropout; 另外可以对self.enc_pos_embedding和self.dec_pos_embedding进行改动，将其分解成position + dimension，有助于减小参数量。

**Comment by lilpeng-xxxl** [comment]
> 可以尝试减小d_model, d_ff, n_heads, e_layers; 增大dropout; 另外可以对self.enc_pos_embedding和self.dec_pos_embedding进行改动，将其分解成position + dimension，有助于减小参数量。

感谢你的回答，不过我不是很理解如何将位置编码层分解成position + dimension，可以请你进一步解释吗？

**Comment by YunhaoZhang-Mars** [comment]
我们现在使用形状为[data_dim, seg_num, d_model]的变量进行位置编码，可以考虑使用形状为[data_dim, 1, d_model]的变量标记dimension，使用[1, seg_num, d_model]的变量标记position，两个tensor相加得到最终的位置编码。

**Comment by lilpeng-xxxl** [comment]
> 我们现在使用形状为[data_dim, seg_num, d_model]的变量进行位置编码，可以考虑使用形状为[data_dim, 1, d_model]的变量标记dimension，使用[1, seg_num, d_model]的变量标记position，两个tensor相加得到最终的位置编码。

感谢你的回答，我会尝试采取你的建议。
