### ISSUE TITLE
About "Cross Time Stage: Directly apply MSA to each dimension"

### ISSUE THREAD

**Issue by HarryHsing** [Thinklab-SJTU/Crossformer#2]
Thank you for your great work!

If we want to compute self-attention across time, should it be "(b seg_num) ts_d d_model" as the input shape?

https://github.com/Thinklab-SJTU/Crossformer/blob/fd0f601319e21d8ad6e058403927a11e75ed13ef/cross_models/attn.py#L98

**Comment by YunhaoZhang-Mars** [comment]
Here `ts_d` indicates the number of dimensions of the time series (i.e. $D$ in the paper) and `seg_num` indicates the number of segments (i.e. $\frac{T}{L_{seg}}$ for the first layer). Thus if we want to compute self-attention across time, we need to reshape it into $[batch \times D, \frac{T}{L_{seg}}, hidden]$, that is `(b ts_d) seg_num d_model`.

**Comment by HarryHsing** [comment]
> Here `ts_d` indicates the number of dimensions of the time series (i.e. D in the paper) and `seg_num` indicates the number of segments (i.e. TLseg for the first layer). Thus if we want to compute self-attention across time, we need to reshape it into [batch×D,TLseg,hidden], that is `(b ts_d) seg_num d_model`.

Got it, thank you very much for your prompt reply!
