### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by georgesmiaka** [Thinklab-SJTU/Crossformer#20]
![Screenshot from 2024-02-20 13-38-51](https://github.com/Thinklab-SJTU/Crossformer/assets/125093286/517c8ac5-2e9d-456d-866a-4123cc41492a)
Hello, thanks for sharing your code. I'm doing my master's thesis on the model's interpretability in the context of Time series prediction. I believe that your model could be a good alternative for my research. 
First, I wanted to ask how you get the plot above?

**Comment by YunhaoZhang-Mars** [comment]
This is the visualization of one forecasting instance of ETTm1 dataset.

To get this, you can run `main_crossformer.py` with the argument `--save_pred`. In this way, all test instances and corresponding ground truth values will be saved. You can illustrate them with matplotlib.

**Comment by georgesmiaka** [comment]
> This is the visualization of one forecasting instance of ETTm1 dataset.
> 
> To get this, you can run `main_crossformer.py` with the argument `--save_pred`. In this way, all test instances and corresponding ground truth values will be saved. You can illustrate them with matplotlib.

Thank you for your response. I've tried using my own dataset and ran the main_crossformer.py script with the --saved_pred option as you suggested. After running the script, I noticed that two files were generated in the map results: pred.npy and true.npy. The pred.npy file has a shape of (65979, 24, 6), and the true.npy file also has a shape of (65979, 24, 6). I'm not entirely sure how to interpret these files. Could you please provide an explanation?

Here's an overview of my dataset:
![Screenshot from 2024-02-20 15-18-28](https://github.com/Thinklab-SJTU/Crossformer/assets/125093286/a5419c40-09e5-4d4d-ad40-f688f9d62bf8)

If I want to visualize a specific forecasting instance, such as pos.x, how can I do that using the true.npy and pred.npy files? Any further clarification on this matter would be greatly appreciated.

Thank you in advance for your assistance.
// Georges

**Comment by VigneshwaranMahadevan** [comment]
65979, 24, 6
65979 is the number of test data - so probably 10% of the your whole data
24 is tau which is default to 24 data points - It means you are forecasting for 24 points in the future using in_len of 96 ( which is the default)
6 is your Dimension - your 6 columns

pred is what the model predicted , true is the actual data you have

If you want to visualise pos.x for example, its index is 4 
So you can do pred[:,0,4] to get the one-step prediction ( that's why 0 in second dimension) of the 5th column (0-based indexing)

**Comment by georgesmiaka** [comment]
@VigneshwaranMahadevan thank you very much 🙏🏽
