### ISSUE TITLE
Tools used to create model illustrations

### ISSUE THREAD

**Issue by FishCatCake** [Thinklab-SJTU/Crossformer#27]
Hi, thanks for making your great work open-source!

I have read your paper and really like the way you sketch the illustrations for model structures. 

May i Know the tools you used to create those illustrations?

Thanks again.

**Comment by YunhaoZhang-Mars** [comment]
Thanks for your attention. All the model structures are drawn using PowerPoint.

**Comment by FishCatCake** [comment]
> Thanks for your attention. All the model structures are drawn using PowerPoint.

Got it, thanks for your quick reply.
