### ISSUE TITLE
inverse_transform

### ISSUE THREAD

**Issue by houzimm** [Thinklab-SJTU/Crossformer#3]
源代码没有设置inverse_transform，反归一化后更能看出实际预测效果。

**Comment by YunhaoZhang-Mars** [comment]
在main_crossformer.py中我们与之前的Informer，Autoformer，Fedformer等工作对齐设定，衡量的是归一化后的各项指标。这主要是出于不同维度的数据scale可能差异比较大的考虑：假设有两个维度，维度1的数值在[-1,1]之间，维度2在[-100,100]之间，如果测量原始scale的指标，则模型只需要对维度1输出常数0而不做预测即可取得较好的结果。因此反归一化后的指标并不能完全反应预测准确性。
在eval_crossformer.py中我们设置了反归一化的选项，用户可以通过--inverse来衡量一个训练好的模型在原始scale上的各项指标。
