### ISSUE TITLE
关于weather数据集的问题

### ISSUE THREAD

**Issue by vaeaea** [Thinklab-SJTU/Crossformer#4]
您好，针对天气数据集，我查阅了您的实验部分的结果，发现表一中显示的各个基线模型  在天气数据集中的的损失  似乎与其原始论文中给出的结果相比偏高，例如FEDformer在其原始文章中给出的在720个预测时间步下的损失分别为0.403和0.428，但是在表一中显示的损失分别为0.562和0.557，请问是否发生了什么错误，或者是有什么特殊的原因导致的吗？
![image](https://user-images.githubusercontent.com/95179140/229843498-84e2ea17-5bac-489b-b84f-1a7893780e14.png)

![image](https://user-images.githubusercontent.com/95179140/229841986-0b337ff2-3c30-4231-a486-2840f45fd7a0.png)

**Comment by vaeaea** [comment]
交通数据集中的损失就和原始文献中的一致，因此是否发生了意外的错误？

**Comment by YunhaoZhang-Mars** [comment]
论文中的WTH数据集取自Informer中维度为12的Weather（并且训练/验证/测试集的划分也与Informer保持一致），而不是Autoformer和Fedformer中使用的21维的数据集。这一点我们在论文原文和readme中也已经提到，具体的实验设置可以参考Appendix部分。
